name: Jarvis Cron

on:
  schedule:
    - cron: '* * * * *' # Run every minute
  repository_dispatch:
    types: [build_status]
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, closed, reopened, synchronize]
  create: # Branch or tag creation
  delete: # Branch or tag deletion

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: node scripts/check.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          EVENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
